# This is a basic workflow to help you get started with Actions

name: Doc Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    # Runs a single command using the runners shell
    - name: Prepare build environment
      run: sudo apt install mkdocs

    # Runs a set of commands using the runners shell
    - name: Build the doc
      run: mkdocs build
    
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
